name: "pre-release"

on:
  push:
    branches:
      - "main"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: 17
        java-package: jdk+fx

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v4
      with:
        gradle-version: wrapper

    - name: Execute Windows Gradle build
      run: ./gradlew -Dplatform=windows shadowJar
    - name: Execute Linux Gradle build
      run: ./gradlew -Dplatform=linux shadowJar

    - name: Make Github release with build artifacts
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Development Build"
        files: |
          dist/*

